name: Make PDF

on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create document
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt install -y  texlive-bibtex-extra biber texlive-lang-english texlive-full
    - name: Convert to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.0.0
      with:
        texFile: ./main.tex
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: main.pdf
